export const FETCH_STORIES = 'FETCH_STORIES';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_STORIES_FAILURE = 'FETCH_STORIES_FAILURE';

export const FAVORITE_STORY = 'FAVORITE_STORY';
export const UNFAVORITE_STORY = 'UNFAVORITE_STORY';
